openapi: 3.0.0
info:
  title: Node Checker API (POKT Lint)
  version: 1.0.0
servers:
  - url: https://2eqrf8goof.execute-api.us-east-1.amazonaws.com/test
  - url: https://2eqrf8goof.execute-api.us-east-1.amazonaws.com/prod
paths:
  /relay-test:
    post:
      tags:
        - default
      summary: Relay Tests
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: ["node_url"]
              properties:
                node_url:
                  type: string
                  description: "The base url of the node to run tests for. Must include protocol and hostname."
                  example: https://node-000.pokt.mynodes.com
                chains:
                  type: array
                  items:
                    type: string
                    description: "Array of chain IDs as described in the [official documentation](https://docs.pokt.network/home/resources/references/supported-blockchains). If blank, node_id param is required."
                    example: ["0001", "0003"]
                node_id:
                  type: string
                  description: The id (address) of the node. Ignored if chains param is set.
                  example: 4fdb144edcfd0d44be506facxxxxxxxxxxxxxxxx
              example:
                node_url: https://node-000.ocean1.pokt.tools
                node_id: 4fdb144edcfd0d44be506facxxxxxxxxxxxxxxxx
                chain_ids:
                  - '0001'
      responses:
        '200':
          description: Successful response is a map of chain IDs to response data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  "0001":
                    type: object
                    properties:
                      chain_id:
                        type: string
                      chain_name:
                        type: string
                      success:
                        type: boolean
                      status_code:
                        type: integer
                      message:
                        type: string
                      duration_ms:
                        type: number
                      relay_request:
                        type: object
                        properties:
                          data:
                            type: object
                            description: JSON payload that was sent to the RPC endpoint
                          method:
                            type: string
                            #descriptiom: HTTP method the RPC endpoint was called with
                          path:
                            type: string
                            description: The RPC endpoint path that was called
                          headers:
                            type: object
                            description: a key value pair map of additional headers that were sent in the RPC request
                      relay_responses:
                        type: array
                        items:
                          type: object
                          properties:
                            status_code:
                              type: integer
                              description: the HTTP status code of the relay response
                            data:
                              type: object
                              description: the value of the relay response
                example:
                  "0001":
                    chain_id: "0001"
                    chain_name: "POKT mainnet"
                    success: true
                    status_code: 200
                    message: "OK"
                    duration_ms: 59.941
                    relay_request:
                      data: {}
                      method: "POST"
                      path: "/v1/query/height"
                      headers: null
                    relay_responses: [
                      {
                        duration_ms: 59.941,
                        response: {
                          status_code: 200,
                          data: {
                            height: 52844

                          }
                        }

                      }
                    ]


  /ping-test:
    post:
      tags:
        - default
      summary: Ping Test
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: ["node_url"]
              properties:
                node_url:
                  type: string
                  description: "the base url of a pocket node. Pings are sent to `{node_url}/v1`"
                num_pings:
                  type: integer
                  description: "(optional) the number of pings to send. Max is 30, default is 10."
              example:
                node_url: https://node-000.pokt.mynodes.com
                num_pings: 25

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  num_sent:
                    type: integer
                  num_ok:
                    type: integer
                  min_time_ms:
                    type: number
                  max_time_ms:
                    type: number
                  avg_time_ms:
                    type: number
                  results:
                    type: array
                    items:
                      type: object
                example:
                  num_sent: 3
                  num_ok: 3
                  min_time_ms: 14.228
                  max_time_ms: 69.566
                  avg_time_ms: 32.77
                  "results": [
                    {
                      "duration_ms": 69.566,
                      "status_code": 200
                    },
                    {
                      "duration_ms": 14.518,
                      "status_code": 200
                    },
                    {
                      "duration_ms": 14.228,
                      "status_code": 200
                    }
                  ]
                    