package pocket

const (
	ChainIDAVAX                = "0003"
	ChainIDBSC                 = "0004"
	ChainIDBSCArchival         = "0010"
	ChainIDBoba                = "0048"
	ChainIDDeFiKingdoms        = "03DF"
	ChainIDSwimmer             = "03CB"
	ChainIDETH                 = "0021"
	ChainIDETHArchival         = "0022"
	ChainIDAVAXArchival        = "00A3"
	ChainIDETHArchivalTrace    = "0028"
	ChainIDETHGoerli           = "0026"
	ChainIDETHKovan            = "0024"
	ChainIDETHRinkeby          = "0025"
	ChainIDETHRopsten          = "0023"
	ChainIDFantom              = "0049"
	ChainIDFUSE                = "0005"
	ChainIDFUSEArchival        = "000A"
	ChainIDGnosisChain         = "0027"
	ChainIDAlgorand            = "0029"
	ChainIDGnosisChainArchival = "000C"
	ChainIDHarmonyShard0       = "0040"
	ChainIDIoTeX               = "0044"
	ChainIDOKExChain           = "0047"
	ChainIDPOKT                = "0001"
	ChainIDPolygon             = "0009"
	ChainIDPolygonArchival     = "000B"
	ChainIDSolana              = "0006"

	// non-revenue

	ChainIDAlgorandArchival        = "000D"
	ChainIDAlgorandTestnet         = "0045"
	ChainIDAlgorandTestnetArchival = "0A45"
	ChainIDArweave                 = "0030"
	ChainIDAVAXFuji                = "000E"
	ChainIDBSCTestnet              = "0011"
	ChainIDBSCTestnetArchival      = "0012"
	ChainIDEvmos                   = "0046"
	ChainIDHarmonyShard0Archival   = "0A40"
	ChainIDHarmonyShard1           = "0041"
	ChainIDHarmonyShard1Archival   = "0A41"
	ChainIDHarmonyShard2           = "0042"
	ChainIDHarmonyShard2Archival   = "0A42"
	ChainIDHarmonyShard3           = "0043"
	ChainIDHarmonyShard3Archival   = "0A43"
	ChainIDMoonbeam                = "0050"
	ChainIDMoonriver               = "0051"
	ChainIDNEAR                    = "0052"
	ChainIDPolygonMumbai           = "000F"
	ChainIDPolygonMumbaiArchival   = "00AF"
	ChainIDSolanaTestnet           = "0031"
)
